-- GENERADO desde commerce/catalog/catalog.js con commerce/tools/gen-seed.mjs. No editar a mano.
begin;
insert into public.catalog_versions (version, notes) values (1, 'Catálogo inicial') on conflict do nothing;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('pack_debut', 'COSMETIC_PACK', 'active', 'Pack Debut', array['cosmetic.debut_pack']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('pack_debut', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('pack_street', 'COSMETIC_PACK', 'active', 'Street Pack', array['cosmetic.street_pack']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('pack_street', 'EUR', 199) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('pack_pro', 'COSMETIC_PACK', 'active', 'Pro Pack', array['cosmetic.pro_pack']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('pack_pro', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('pack_luxury', 'COSMETIC_PACK', 'active', 'Luxury Pack', array['cosmetic.luxury_pack']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('pack_luxury', 'EUR', 399) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('pack_magnate', 'COSMETIC_PACK', 'active', 'Magnate Pack', array['cosmetic.magnate_pack']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('pack_magnate', 'EUR', 499) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('founder_pack', 'SUPPORTER_PACK', 'active', 'Founder Pack', array['cosmetic.founder_pack','slots.extra_3','ads.remove_interstitial']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('founder_pack', 'EUR', 499) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('club_pack_puerto', 'COSMETIC_PACK', 'active', 'Pack UD Puerto', array['cosmetic.club_puerto']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('club_pack_puerto', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('club_pack_costa', 'COSMETIC_PACK', 'active', 'Pack Real Costa', array['cosmetic.club_costa']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('club_pack_costa', 'EUR', 199) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('club_pack_atletico', 'COSMETIC_PACK', 'active', 'Pack Atlético Ciudad', array['cosmetic.club_atletico']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('club_pack_atletico', 'EUR', 199) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('champion_pack_copa', 'COSMETIC_PACK', 'active', 'Pack Campeón · Copa Federación', array['cosmetic.champion_copa']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('champion_pack_copa', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('champion_pack_europa', 'COSMETIC_PACK', 'active', 'Pack Campeón · Copa de Europa', array['cosmetic.champion_europa']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('champion_pack_europa', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('champion_pack_mundial', 'COSMETIC_PACK', 'active', 'Pack Campeón · Mundial', array['cosmetic.champion_mundial']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('champion_pack_mundial', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('champion_pack_liga', 'COSMETIC_PACK', 'active', 'Pack Campeón · Liga', array['cosmetic.champion_liga']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('champion_pack_liga', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('remove_ads', 'REMOVE_ADS', 'active', 'Quitar anuncios', array['ads.remove_interstitial']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('remove_ads', 'EUR', 399) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('extra_save_slots_3', 'SAVE_SLOTS', 'active', '+3 carreras', array['slots.extra_3']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('extra_save_slots_3', 'EUR', 199) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('sport_climbing', 'SPORT_EXPANSION', 'testing', 'Escalada', array['sport.climbing']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('sport_climbing', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('sport_tennis', 'SPORT_EXPANSION', 'coming_soon', 'Tenis', array['sport.tennis']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('sport_tennis', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('sport_basketball', 'SPORT_EXPANSION', 'coming_soon', 'Basket', array['sport.basketball']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('sport_basketball', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('sport_skate', 'SPORT_EXPANSION', 'coming_soon', 'Skate', array['sport.skate']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('sport_skate', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('sport_surf', 'SPORT_EXPANSION', 'coming_soon', 'Surf', array['sport.surf']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('sport_surf', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('sports_bundle', 'BUNDLE', 'coming_soon', 'Todos los deportes', array['sport.climbing','sport.tennis','sport.basketball','sport.skate','sport.surf']::text[], null, array['sport_climbing','sport_tennis','sport_basketball','sport_skate','sport_surf']::text[], true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('sports_bundle', 'EUR', 899) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('expansion_club_owner', 'SYSTEM_EXPANSION', 'coming_soon', 'Propietario de club', array['expansion.club_owner']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('expansion_club_owner', 'EUR', 399) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('expansion_real_estate', 'SYSTEM_EXPANSION', 'coming_soon', 'Imperio inmobiliario', array['expansion.real_estate']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('expansion_real_estate', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('expansion_sports_agency', 'SYSTEM_EXPANSION', 'coming_soon', 'Agencia de deportistas', array['expansion.sports_agency']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('expansion_sports_agency', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('expansion_events', 'SYSTEM_EXPANSION', 'coming_soon', 'Organizador de eventos', array['expansion.events']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('expansion_events', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('expansion_media', 'SYSTEM_EXPANSION', 'coming_soon', 'Media & Sports', array['expansion.media']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('expansion_media', 'EUR', 299) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('empire_bundle', 'BUNDLE', 'coming_soon', 'Empire Bundle', array['expansion.club_owner','expansion.real_estate','expansion.sports_agency','expansion.events']::text[], null, array['expansion_club_owner','expansion_real_estate','expansion_sports_agency','expansion_events']::text[], true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('empire_bundle', 'EUR', 699) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_world_football_president', 'PRESTIGE_CAREER', 'testing', 'Presidente de la Federación Mundial de Fútbol', array['prestige.world_football_president']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_world_football_president', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_world_climbing_president', 'PRESTIGE_CAREER', 'coming_soon', 'Presidente de la Federación Mundial de Escalada', array['prestige.world_climbing_president']::text[], '{"all":["sport.climbing"]}'::jsonb, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_world_climbing_president', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_world_basket_president', 'PRESTIGE_CAREER', 'coming_soon', 'Presidente de la Federación Mundial de Baloncesto', array['prestige.world_basket_president']::text[], '{"all":["sport.basketball"]}'::jsonb, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_world_basket_president', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_world_tennis_president', 'PRESTIGE_CAREER', 'coming_soon', 'Presidente de la Federación Mundial de Tenis', array['prestige.world_tennis_president']::text[], '{"all":["sport.tennis"]}'::jsonb, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_world_tennis_president', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_league_president', 'PRESTIGE_CAREER', 'coming_soon', 'Presidente de la Liga', array['prestige.league_president']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_league_president', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_national_federation', 'PRESTIGE_CAREER', 'coming_soon', 'Presidente de la Federación Nacional', array['prestige.national_federation']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_national_federation', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_national_coach', 'PRESTIGE_CAREER', 'coming_soon', 'Seleccionador nacional', array['prestige.national_coach']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_national_coach', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_sporting_director', 'PRESTIGE_CAREER', 'coming_soon', 'Director deportivo', array['prestige.sporting_director']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_sporting_director', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_agent', 'PRESTIGE_CAREER', 'coming_soon', 'Agente internacional', array['prestige.agent']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_agent', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_referee', 'PRESTIGE_CAREER', 'coming_soon', 'Árbitro internacional', array['prestige.referee']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_referee', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_media_personality', 'PRESTIGE_CAREER', 'coming_soon', 'Comentarista / periodista', array['prestige.media_personality']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_media_personality', 'EUR', 99) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_world_sports_committee', 'PRESTIGE_CAREER', 'coming_soon', 'Presidente del Comité Mundial del Deporte', array['prestige.world_sports_committee']::text[], '{"anyCount":{"n":2,"of":["sport.climbing","sport.tennis","sport.basketball","sport.skate","sport.surf"]}}'::jsonb, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_world_sports_committee', 'EUR', 199) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('prestige_bundle', 'BUNDLE', 'coming_soon', 'Prestige Bundle', array['prestige.world_football_president','prestige.league_president','prestige.national_federation','prestige.national_coach','prestige.sporting_director','prestige.agent','prestige.referee','prestige.media_personality']::text[], null, array['prestige_world_football_president','prestige_league_president','prestige_national_federation','prestige_national_coach','prestige_sporting_director','prestige_agent','prestige_referee','prestige_media_personality']::text[], true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.product_prices (product_id, currency, amount_minor) values ('prestige_bundle', 'EUR', 399) on conflict (product_id, currency) do update set amount_minor = excluded.amount_minor;
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('promo_press', 'PROMO', 'active', 'Insignia de prensa', array['cosmetic.press_badge']::text[], null, null, true, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.products (id, type, status, name, entitlements, requires, bundle_contents, one_time, catalog_version) values ('season_pass', 'FUTURE_SUBSCRIPTION', 'draft', 'Pase de temporada', '{}'::text[], null, null, false, 1)
  on conflict (id) do update set type = excluded.type, status = excluded.status, name = excluded.name, entitlements = excluded.entitlements, requires = excluded.requires, bundle_contents = excluded.bundle_contents, catalog_version = excluded.catalog_version, updated_at = now();
insert into public.remote_config (environment, key, value) values ('development', 'commerce', '{"environment":"development","commerceEnabled":true,"stripeEnabled":true,"appleBillingEnabled":false,"googleBillingEnabled":false,"rewardedEnabled":true,"interstitialEnabled":true,"prestigeEnabled":true,"sportExpansionEnabled":true,"stripeTaxEnabled":false,"requireWithdrawalConsent":true,"liveModeAllowed":false,"visibleSkus":null,"hiddenSkus":[],"maxFeatured":3,"refunds":{"partialRevokes":false},"disputes":{"suspend":true},"ios":{"externalPurchase":{"enabled":false,"storefronts":[]}},"android":{"alternativeBilling":{"enabled":false,"countries":[],"mode":null}},"rewarded":{"placements":["store_discount","store_special_offer","small_energy","offline_business_bonus","cosmetic_reward"],"dailyCap":6,"minigameLife":false},"rateLimits":{"checkout":[10,600],"promo":[5,3600],"restore":[6,600],"sync":[60,600]},"experiments":{}}'::jsonb) on conflict (environment, key) do nothing;
insert into public.remote_config (environment, key, value) values ('staging', 'commerce', '{"environment":"staging","commerceEnabled":true,"stripeEnabled":true,"appleBillingEnabled":false,"googleBillingEnabled":false,"rewardedEnabled":true,"interstitialEnabled":true,"prestigeEnabled":true,"sportExpansionEnabled":true,"stripeTaxEnabled":false,"requireWithdrawalConsent":true,"liveModeAllowed":false,"visibleSkus":null,"hiddenSkus":[],"maxFeatured":3,"refunds":{"partialRevokes":false},"disputes":{"suspend":true},"ios":{"externalPurchase":{"enabled":false,"storefronts":[]}},"android":{"alternativeBilling":{"enabled":false,"countries":[],"mode":null}},"rewarded":{"placements":["store_discount","store_special_offer","small_energy","offline_business_bonus","cosmetic_reward"],"dailyCap":6,"minigameLife":false},"rateLimits":{"checkout":[10,600],"promo":[5,3600],"restore":[6,600],"sync":[60,600]},"experiments":{}}'::jsonb) on conflict (environment, key) do nothing;
insert into public.remote_config (environment, key, value) values ('production', 'commerce', '{"environment":"production","commerceEnabled":true,"stripeEnabled":true,"appleBillingEnabled":false,"googleBillingEnabled":false,"rewardedEnabled":true,"interstitialEnabled":true,"prestigeEnabled":true,"sportExpansionEnabled":true,"stripeTaxEnabled":false,"requireWithdrawalConsent":true,"liveModeAllowed":false,"visibleSkus":null,"hiddenSkus":[],"maxFeatured":3,"refunds":{"partialRevokes":false},"disputes":{"suspend":true},"ios":{"externalPurchase":{"enabled":false,"storefronts":[]}},"android":{"alternativeBilling":{"enabled":false,"countries":[],"mode":null}},"rewarded":{"placements":["store_discount","store_special_offer","small_energy","offline_business_bonus","cosmetic_reward"],"dailyCap":6,"minigameLife":false},"rateLimits":{"checkout":[10,600],"promo":[5,3600],"restore":[6,600],"sync":[60,600]},"experiments":{}}'::jsonb) on conflict (environment, key) do nothing;
commit;
